"""Built-in separator, turbine and associated instrumentation components.

Original illustrative artwork. Process and measurement ports share the native
renderer and routing contract; these are not certified engineering symbols.
"""

CATALOG = {'vortex_separator': {'label': 'Vortex phase separator',
                      'prefix': 'VPS',
                      'category': 'Separation & Treatment',
                      'ports': {'liquid_in': [-45, 0],
                                'gas_in': [45, 0],
                                'gas_out': [0, -45],
                                'liquid_out': [0, 45]},
                      'port_kinds': {'liquid_in': 'process',
                                     'gas_in': 'process',
                                     'gas_out': 'process',
                                     'liquid_out': 'process'},
                      'routing_bounds': [-30, -32, 30, 32],
                      'artwork': [{'kind': 'rect', 'rect': [-30, -32, 60, 64]},
                                  {'kind': 'polyline', 'points': [[-45, 0], [-30, 0]]},
                                  {'kind': 'polyline', 'points': [[30, 0], [45, 0]]},
                                  {'kind': 'polyline', 'points': [[0, -45], [0, -32]]},
                                  {'kind': 'polyline', 'points': [[0, 32], [0, 45]]},
                                  {'kind': 'polyline',
                                   'points': [[-20, -18],
                                              [18, -18],
                                              [18, -5],
                                              [-15, -5],
                                              [-15, 10],
                                              [10, 10],
                                              [10, 20],
                                              [0, 20]]}]},
 'turbine': {'label': 'Turbine / expander',
             'prefix': 'STB',
             'category': 'Pumps & Compressors',
             'ports': {'inlet': [-45, 0], 'outlet': [0, 45], 'shaft': [45, 0]},
             'port_kinds': {'inlet': 'process', 'outlet': 'process', 'shaft': 'signal'},
             'routing_bounds': [-30, -28, 30, 28],
             'artwork': [{'kind': 'polygon',
                          'points': [[-30, -18], [30, -28], [30, 28], [-30, 18]]},
                         {'kind': 'polyline', 'points': [[-45, 0], [-30, 0]]},
                         {'kind': 'polyline', 'points': [[30, 0], [45, 0]]},
                         {'kind': 'polyline', 'points': [[0, 23], [0, 45]]}]},
 'inline_flowmeter': {'label': 'Inline flowmeter (unspecified technology)',
                      'prefix': 'FM',
                      'category': 'Instrumentation',
                      'ports': {'inlet': [-40, 0], 'outlet': [40, 0]},
                      'port_kinds': {'inlet': 'process', 'outlet': 'process'},
                      'routing_bounds': [-23, -23, 23, 23],
                      'artwork': [{'kind': 'polyline', 'points': [[-40, 0], [-23, 0]]},
                                  {'kind': 'polyline', 'points': [[23, 0], [40, 0]]},
                                  {'kind': 'ellipse', 'rect': [-23, -23, 46, 46]},
                                  {'kind': 'polyline', 'points': [[-9, -12], [-9, 12]]},
                                  {'kind': 'polyline', 'points': [[-9, -12], [10, -12]]},
                                  {'kind': 'polyline', 'points': [[-9, -1], [5, -1]]}]},
 'acoustic_sensor': {'label': 'Ultrasonic acoustic sensor (surface mounted)',
                     'prefix': 'UAC',
                     'category': 'Instrumentation',
                     'ports': {'mount': [0, 40]},
                     'port_kinds': {'mount': 'signal'},
                     'routing_bounds': [-22, -22, 22, 22],
                     'artwork': [{'kind': 'ellipse', 'rect': [-22, -22, 44, 44]},
                                 {'kind': 'polyline',
                                  'points': [[-15, 0], [-8, -8], [0, 8], [8, -8], [15, 0]]},
                                 {'kind': 'polyline', 'points': [[0, 22], [0, 40]]}]},
 'hall_speed_sensor': {'label': 'Hall rotational speed sensor',
                       'prefix': 'EHS',
                       'category': 'Instrumentation',
                       'ports': {'pickup': [-40, 0]},
                       'port_kinds': {'pickup': 'signal'},
                       'routing_bounds': [-22, -18, 22, 18],
                       'artwork': [{'kind': 'rect', 'rect': [-22, -18, 44, 36]},
                                   {'kind': 'polyline', 'points': [[-40, 0], [-22, 0]]},
                                   {'kind': 'polyline', 'points': [[-10, -10], [-10, 10]]},
                                   {'kind': 'polyline', 'points': [[10, -10], [10, 10]]},
                                   {'kind': 'polyline', 'points': [[-10, 0], [10, 0]]}]},
 'heating_coil': {'label': 'Surface heating coil',
                  'prefix': 'HC',
                  'category': 'Heat Transfer',
                  'ports': {'mount': [-40, 0]},
                  'port_kinds': {'mount': 'signal'},
                  'routing_bounds': [-22, -20, 22, 20],
                  'artwork': [{'kind': 'polyline',
                               'points': [[-40, 0],
                                          [-22, 0],
                                          [-16, -16],
                                          [-8, 16],
                                          [0, -16],
                                          [8, 16],
                                          [16, -16],
                                          [22, 0]]}]},
 'humidity_sensor': {'label': 'Humidity sensor',
                     'prefix': 'HS',
                     'category': 'Instrumentation',
                     'ports': {'process': [0, 40]},
                     'port_kinds': {'process': 'process'},
                     'routing_bounds': [-22, -22, 22, 22],
                     'artwork': [{'kind': 'ellipse', 'rect': [-22, -22, 44, 44]},
                                 {'kind': 'polyline', 'points': [[-22, 0], [22, 0]]},
                                 {'kind': 'polyline', 'points': [[0, 22], [0, 40]]}]},
 'thermocouple': {'label': 'Surface thermocouple',
                  'prefix': 'TC',
                  'category': 'Instrumentation',
                  'ports': {'mount': [0, 40]},
                  'port_kinds': {'mount': 'signal'},
                  'routing_bounds': [-22, -22, 22, 22],
                  'artwork': [{'kind': 'ellipse', 'rect': [-22, -22, 44, 44]},
                              {'kind': 'polyline', 'points': [[-10, -8], [10, -8]]},
                              {'kind': 'polyline', 'points': [[0, -8], [0, 12]]},
                              {'kind': 'polyline', 'points': [[0, 22], [0, 40]]}]}}

# Meaning and legacy serialization are separate. These descriptions do not
# silently migrate a saved signal line into a mechanical connection.
for _kind, _port, _meaning in (
    ('turbine','shaft','Mechanical shaft attachment; not an instrument signal terminal.'),
    ('acoustic_sensor','mount','Surface mounting / measurement association; no output signal terminal is modeled.'),
    ('hall_speed_sensor','pickup','Rotating-target sensing association; not a torque-transmitting shaft coupling or output signal terminal.'),
    ('heating_coil','mount','Surface-heating attachment; no heating-fluid circuit or electrical supply is modeled.'),
    ('thermocouple','mount','Surface temperature measurement attachment; no separate output signal terminal is modeled.'),
):
    CATALOG[_kind]['port_meanings'] = {_port: _meaning}

# Legacy prefixes are retained identifiers, not inferred ISA function codes.
for _kind, _meaning in {
    'inline_flowmeter': 'FM is the retained project mnemonic for inline flow measurement; sensing technology and indicating/transmitting functions are unspecified.',
    'acoustic_sensor': 'UAC identifies surface acoustic measurement in this project. The wave is a sensing illustration, not an electrical waveform or an output connection.',
    'hall_speed_sensor': 'EHS identifies Hall-effect rotational speed sensing in this project; H is a technology pictogram, not an ISA functional identifier.',
    'humidity_sensor': 'HS means humidity sensor in this legacy library, not hand switch. No control, switch action or installation location is implied.',
    'thermocouple': 'TC means surface thermocouple in this legacy library, not temperature controller. T depicts temperature sensing; no control function is modeled.',
    'heating_coil': 'Illustrative surface-heating attachment, not a fluid heating coil. HC is a project equipment mnemonic.',
    'vortex_separator': 'Generic equipment package for the named vortex separation duty, not a standardized internal-flow symbol. liquid_in and gas_in are separate named feeds; gas_out and liquid_out are phase outlets. Internal geometry is not modeled.',
}.items():
    CATALOG[_kind]['symbol_notes'] = [_meaning]

# The former stepped maze had no established physical or symbolic meaning.
# Retain the package boundary and its four service leads, without fictitious internals.
CATALOG['vortex_separator']['artwork'] = CATALOG['vortex_separator']['artwork'][:5]
